/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package salutem.visit.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Location service. Represents a row in the &quot;visit_Location&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link salutem.visit.model.impl.LocationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link salutem.visit.model.impl.LocationImpl}.
 * </p>
 *
 * @author Aneta Andrzejewska
 * @see Location
 * @see salutem.visit.model.impl.LocationImpl
 * @see salutem.visit.model.impl.LocationModelImpl
 * @generated
 */
public interface LocationModel extends BaseModel<Location> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a location model instance should use the {@link Location} interface instead.
	 */

	/**
	 * Returns the primary key of this location.
	 *
	 * @return the primary key of this location
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this location.
	 *
	 * @param primaryKey the primary key of this location
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the location ID of this location.
	 *
	 * @return the location ID of this location
	 */
	public long getLocationId();

	/**
	 * Sets the location ID of this location.
	 *
	 * @param locationId the location ID of this location
	 */
	public void setLocationId(long locationId);

	/**
	 * Returns the patient ID of this location.
	 *
	 * @return the patient ID of this location
	 */
	public long getPatientId();

	/**
	 * Sets the patient ID of this location.
	 *
	 * @param patientId the patient ID of this location
	 */
	public void setPatientId(long patientId);

	/**
	 * Returns the day of this location.
	 *
	 * @return the day of this location
	 */
	public int getDay();

	/**
	 * Sets the day of this location.
	 *
	 * @param day the day of this location
	 */
	public void setDay(int day);

	/**
	 * Returns the month of this location.
	 *
	 * @return the month of this location
	 */
	public int getMonth();

	/**
	 * Sets the month of this location.
	 *
	 * @param month the month of this location
	 */
	public void setMonth(int month);

	/**
	 * Returns the year of this location.
	 *
	 * @return the year of this location
	 */
	public int getYear();

	/**
	 * Sets the year of this location.
	 *
	 * @param year the year of this location
	 */
	public void setYear(int year);

	/**
	 * Returns the lat of this location.
	 *
	 * @return the lat of this location
	 */
	public double getLat();

	/**
	 * Sets the lat of this location.
	 *
	 * @param lat the lat of this location
	 */
	public void setLat(double lat);

	/**
	 * Returns the lon of this location.
	 *
	 * @return the lon of this location
	 */
	public double getLon();

	/**
	 * Sets the lon of this location.
	 *
	 * @param lon the lon of this location
	 */
	public void setLon(double lon);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(salutem.visit.model.Location location);

	@Override
	public int hashCode();

	@Override
	public CacheModel<salutem.visit.model.Location> toCacheModel();

	@Override
	public salutem.visit.model.Location toEscapedModel();

	@Override
	public salutem.visit.model.Location toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}