/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package salutem.visit.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Regression service. Represents a row in the &quot;visit_Regression&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link salutem.visit.model.impl.RegressionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link salutem.visit.model.impl.RegressionImpl}.
 * </p>
 *
 * @author Aneta Andrzejewska
 * @see Regression
 * @see salutem.visit.model.impl.RegressionImpl
 * @see salutem.visit.model.impl.RegressionModelImpl
 * @generated
 */
public interface RegressionModel extends BaseModel<Regression> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a regression model instance should use the {@link Regression} interface instead.
	 */

	/**
	 * Returns the primary key of this regression.
	 *
	 * @return the primary key of this regression
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this regression.
	 *
	 * @param primaryKey the primary key of this regression
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the regression ID of this regression.
	 *
	 * @return the regression ID of this regression
	 */
	public long getRegressionId();

	/**
	 * Sets the regression ID of this regression.
	 *
	 * @param regressionId the regression ID of this regression
	 */
	public void setRegressionId(long regressionId);

	/**
	 * Returns the patient ID of this regression.
	 *
	 * @return the patient ID of this regression
	 */
	public long getPatientId();

	/**
	 * Sets the patient ID of this regression.
	 *
	 * @param patientId the patient ID of this regression
	 */
	public void setPatientId(long patientId);

	/**
	 * Returns the doctor ID of this regression.
	 *
	 * @return the doctor ID of this regression
	 */
	public long getDoctorId();

	/**
	 * Sets the doctor ID of this regression.
	 *
	 * @param doctorId the doctor ID of this regression
	 */
	public void setDoctorId(long doctorId);

	/**
	 * Returns the minimum list of this regression.
	 *
	 * @return the minimum list of this regression
	 */
	@AutoEscape
	public String getMinimumList();

	/**
	 * Sets the minimum list of this regression.
	 *
	 * @param minimumList the minimum list of this regression
	 */
	public void setMinimumList(String minimumList);

	/**
	 * Returns the maximum list of this regression.
	 *
	 * @return the maximum list of this regression
	 */
	@AutoEscape
	public String getMaximumList();

	/**
	 * Sets the maximum list of this regression.
	 *
	 * @param maximumList the maximum list of this regression
	 */
	public void setMaximumList(String maximumList);

	/**
	 * Returns the chosen k of this regression.
	 *
	 * @return the chosen k of this regression
	 */
	public int getChosenK();

	/**
	 * Sets the chosen k of this regression.
	 *
	 * @param chosenK the chosen k of this regression
	 */
	public void setChosenK(int chosenK);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(salutem.visit.model.Regression regression);

	@Override
	public int hashCode();

	@Override
	public CacheModel<salutem.visit.model.Regression> toCacheModel();

	@Override
	public salutem.visit.model.Regression toEscapedModel();

	@Override
	public salutem.visit.model.Regression toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}