/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package salutem.visit.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Time service. Represents a row in the &quot;visit_Time&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link salutem.visit.model.impl.TimeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link salutem.visit.model.impl.TimeImpl}.
 * </p>
 *
 * @author Aneta Andrzejewska
 * @see Time
 * @see salutem.visit.model.impl.TimeImpl
 * @see salutem.visit.model.impl.TimeModelImpl
 * @generated
 */
public interface TimeModel extends BaseModel<Time> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a time model instance should use the {@link Time} interface instead.
	 */

	/**
	 * Returns the primary key of this time.
	 *
	 * @return the primary key of this time
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this time.
	 *
	 * @param primaryKey the primary key of this time
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the time ID of this time.
	 *
	 * @return the time ID of this time
	 */
	public long getTimeId();

	/**
	 * Sets the time ID of this time.
	 *
	 * @param timeId the time ID of this time
	 */
	public void setTimeId(long timeId);

	/**
	 * Returns the entry uuid of this time.
	 *
	 * @return the entry uuid of this time
	 */
	@AutoEscape
	public String getEntryUuid();

	/**
	 * Sets the entry uuid of this time.
	 *
	 * @param entryUuid the entry uuid of this time
	 */
	public void setEntryUuid(String entryUuid);

	/**
	 * Returns the group ID of this time.
	 *
	 * @return the group ID of this time
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this time.
	 *
	 * @param groupId the group ID of this time
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the doctor ID of this time.
	 *
	 * @return the doctor ID of this time
	 */
	public long getDoctorId();

	/**
	 * Sets the doctor ID of this time.
	 *
	 * @param doctorId the doctor ID of this time
	 */
	public void setDoctorId(long doctorId);

	/**
	 * Returns the patient ID of this time.
	 *
	 * @return the patient ID of this time
	 */
	public long getPatientId();

	/**
	 * Sets the patient ID of this time.
	 *
	 * @param patientId the patient ID of this time
	 */
	public void setPatientId(long patientId);

	/**
	 * Returns the visit day of this time.
	 *
	 * @return the visit day of this time
	 */
	public int getVisitDay();

	/**
	 * Sets the visit day of this time.
	 *
	 * @param visitDay the visit day of this time
	 */
	public void setVisitDay(int visitDay);

	/**
	 * Returns the visit month of this time.
	 *
	 * @return the visit month of this time
	 */
	public int getVisitMonth();

	/**
	 * Sets the visit month of this time.
	 *
	 * @param visitMonth the visit month of this time
	 */
	public void setVisitMonth(int visitMonth);

	/**
	 * Returns the visit year of this time.
	 *
	 * @return the visit year of this time
	 */
	public int getVisitYear();

	/**
	 * Sets the visit year of this time.
	 *
	 * @param visitYear the visit year of this time
	 */
	public void setVisitYear(int visitYear);

	/**
	 * Returns the visit time of this time.
	 *
	 * @return the visit time of this time
	 */
	public int getVisitTime();

	/**
	 * Sets the visit time of this time.
	 *
	 * @param visitTime the visit time of this time
	 */
	public void setVisitTime(int visitTime);

	/**
	 * Returns the visit duration of this time.
	 *
	 * @return the visit duration of this time
	 */
	public int getVisitDuration();

	/**
	 * Sets the visit duration of this time.
	 *
	 * @param visitDuration the visit duration of this time
	 */
	public void setVisitDuration(int visitDuration);

	/**
	 * Returns the was finished of this time.
	 *
	 * @return the was finished of this time
	 */
	public boolean getWasFinished();

	/**
	 * Returns <code>true</code> if this time is was finished.
	 *
	 * @return <code>true</code> if this time is was finished; <code>false</code> otherwise
	 */
	public boolean isWasFinished();

	/**
	 * Sets whether this time is was finished.
	 *
	 * @param wasFinished the was finished of this time
	 */
	public void setWasFinished(boolean wasFinished);

	/**
	 * Returns the was planned of this time.
	 *
	 * @return the was planned of this time
	 */
	public boolean getWasPlanned();

	/**
	 * Returns <code>true</code> if this time is was planned.
	 *
	 * @return <code>true</code> if this time is was planned; <code>false</code> otherwise
	 */
	public boolean isWasPlanned();

	/**
	 * Sets whether this time is was planned.
	 *
	 * @param wasPlanned the was planned of this time
	 */
	public void setWasPlanned(boolean wasPlanned);

	/**
	 * Returns the visit ID of this time.
	 *
	 * @return the visit ID of this time
	 */
	public long getVisitId();

	/**
	 * Sets the visit ID of this time.
	 *
	 * @param visitId the visit ID of this time
	 */
	public void setVisitId(long visitId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(salutem.visit.model.Time time);

	@Override
	public int hashCode();

	@Override
	public CacheModel<salutem.visit.model.Time> toCacheModel();

	@Override
	public salutem.visit.model.Time toEscapedModel();

	@Override
	public salutem.visit.model.Time toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}