/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package salutem.visit.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Visit service. Represents a row in the &quot;visit_Visit&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link salutem.visit.model.impl.VisitModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link salutem.visit.model.impl.VisitImpl}.
 * </p>
 *
 * @author Aneta Andrzejewska
 * @see Visit
 * @see salutem.visit.model.impl.VisitImpl
 * @see salutem.visit.model.impl.VisitModelImpl
 * @generated
 */
public interface VisitModel extends BaseModel<Visit> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a visit model instance should use the {@link Visit} interface instead.
	 */

	/**
	 * Returns the primary key of this visit.
	 *
	 * @return the primary key of this visit
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this visit.
	 *
	 * @param primaryKey the primary key of this visit
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the visit ID of this visit.
	 *
	 * @return the visit ID of this visit
	 */
	public long getVisitId();

	/**
	 * Sets the visit ID of this visit.
	 *
	 * @param visitId the visit ID of this visit
	 */
	public void setVisitId(long visitId);

	/**
	 * Returns the group ID of this visit.
	 *
	 * @return the group ID of this visit
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this visit.
	 *
	 * @param groupId the group ID of this visit
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this visit.
	 *
	 * @return the company ID of this visit
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this visit.
	 *
	 * @param companyId the company ID of this visit
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this visit.
	 *
	 * @return the create date of this visit
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this visit.
	 *
	 * @param createDate the create date of this visit
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this visit.
	 *
	 * @return the modified date of this visit
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this visit.
	 *
	 * @param modifiedDate the modified date of this visit
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the doctor ID of this visit.
	 *
	 * @return the doctor ID of this visit
	 */
	public long getDoctorId();

	/**
	 * Sets the doctor ID of this visit.
	 *
	 * @param doctorId the doctor ID of this visit
	 */
	public void setDoctorId(long doctorId);

	/**
	 * Returns the patient ID of this visit.
	 *
	 * @return the patient ID of this visit
	 */
	public long getPatientId();

	/**
	 * Sets the patient ID of this visit.
	 *
	 * @param patientId the patient ID of this visit
	 */
	public void setPatientId(long patientId);

	/**
	 * Returns the cancelled of this visit.
	 *
	 * @return the cancelled of this visit
	 */
	public boolean getCancelled();

	/**
	 * Returns <code>true</code> if this visit is cancelled.
	 *
	 * @return <code>true</code> if this visit is cancelled; <code>false</code> otherwise
	 */
	public boolean isCancelled();

	/**
	 * Sets whether this visit is cancelled.
	 *
	 * @param cancelled the cancelled of this visit
	 */
	public void setCancelled(boolean cancelled);

	/**
	 * Returns the has happened of this visit.
	 *
	 * @return the has happened of this visit
	 */
	public boolean getHasHappened();

	/**
	 * Returns <code>true</code> if this visit is has happened.
	 *
	 * @return <code>true</code> if this visit is has happened; <code>false</code> otherwise
	 */
	public boolean isHasHappened();

	/**
	 * Sets whether this visit is has happened.
	 *
	 * @param hasHappened the has happened of this visit
	 */
	public void setHasHappened(boolean hasHappened);

	/**
	 * Returns the visit date of this visit.
	 *
	 * @return the visit date of this visit
	 */
	public Date getVisitDate();

	/**
	 * Sets the visit date of this visit.
	 *
	 * @param visitDate the visit date of this visit
	 */
	public void setVisitDate(Date visitDate);

	/**
	 * Returns the start time minutes of this visit.
	 *
	 * @return the start time minutes of this visit
	 */
	public int getStartTimeMinutes();

	/**
	 * Sets the start time minutes of this visit.
	 *
	 * @param startTimeMinutes the start time minutes of this visit
	 */
	public void setStartTimeMinutes(int startTimeMinutes);

	/**
	 * Returns the duration of this visit.
	 *
	 * @return the duration of this visit
	 */
	public int getDuration();

	/**
	 * Sets the duration of this visit.
	 *
	 * @param duration the duration of this visit
	 */
	public void setDuration(int duration);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(salutem.visit.model.Visit visit);

	@Override
	public int hashCode();

	@Override
	public CacheModel<salutem.visit.model.Visit> toCacheModel();

	@Override
	public salutem.visit.model.Visit toEscapedModel();

	@Override
	public salutem.visit.model.Visit toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}