/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package salutem.visit.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the WeightMap service. Represents a row in the &quot;visit_WeightMap&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link salutem.visit.model.impl.WeightMapModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link salutem.visit.model.impl.WeightMapImpl}.
 * </p>
 *
 * @author Aneta Andrzejewska
 * @see WeightMap
 * @see salutem.visit.model.impl.WeightMapImpl
 * @see salutem.visit.model.impl.WeightMapModelImpl
 * @generated
 */
public interface WeightMapModel extends BaseModel<WeightMap> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a weight map model instance should use the {@link WeightMap} interface instead.
	 */

	/**
	 * Returns the primary key of this weight map.
	 *
	 * @return the primary key of this weight map
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this weight map.
	 *
	 * @param primaryKey the primary key of this weight map
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the weight map ID of this weight map.
	 *
	 * @return the weight map ID of this weight map
	 */
	public long getWeightMapId();

	/**
	 * Sets the weight map ID of this weight map.
	 *
	 * @param weightMapId the weight map ID of this weight map
	 */
	public void setWeightMapId(long weightMapId);

	/**
	 * Returns the regression ID of this weight map.
	 *
	 * @return the regression ID of this weight map
	 */
	public long getRegressionId();

	/**
	 * Sets the regression ID of this weight map.
	 *
	 * @param regressionId the regression ID of this weight map
	 */
	public void setRegressionId(long regressionId);

	/**
	 * Returns the key of this weight map.
	 *
	 * @return the key of this weight map
	 */
	@AutoEscape
	public String getKey();

	/**
	 * Sets the key of this weight map.
	 *
	 * @param key the key of this weight map
	 */
	public void setKey(String key);

	/**
	 * Returns the value of this weight map.
	 *
	 * @return the value of this weight map
	 */
	public double getValue();

	/**
	 * Sets the value of this weight map.
	 *
	 * @param value the value of this weight map
	 */
	public void setValue(double value);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(salutem.visit.model.WeightMap weightMap);

	@Override
	public int hashCode();

	@Override
	public CacheModel<salutem.visit.model.WeightMap> toCacheModel();

	@Override
	public salutem.visit.model.WeightMap toEscapedModel();

	@Override
	public salutem.visit.model.WeightMap toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}