/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package salutem.doctor.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Doctor service. Represents a row in the &quot;doctor_Doctor&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link salutem.doctor.model.impl.DoctorModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link salutem.doctor.model.impl.DoctorImpl}.
 * </p>
 *
 * @author Aneta Andrzejewska
 * @see Doctor
 * @see salutem.doctor.model.impl.DoctorImpl
 * @see salutem.doctor.model.impl.DoctorModelImpl
 * @generated
 */
public interface DoctorModel extends BaseModel<Doctor>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a doctor model instance should use the {@link Doctor} interface instead.
	 */

	/**
	 * Returns the primary key of this doctor.
	 *
	 * @return the primary key of this doctor
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this doctor.
	 *
	 * @param primaryKey the primary key of this doctor
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the doctor ID of this doctor.
	 *
	 * @return the doctor ID of this doctor
	 */
	public long getDoctorId();

	/**
	 * Sets the doctor ID of this doctor.
	 *
	 * @param doctorId the doctor ID of this doctor
	 */
	public void setDoctorId(long doctorId);

	/**
	 * Returns the group ID of this doctor.
	 *
	 * @return the group ID of this doctor
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this doctor.
	 *
	 * @param groupId the group ID of this doctor
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this doctor.
	 *
	 * @return the company ID of this doctor
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this doctor.
	 *
	 * @param companyId the company ID of this doctor
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this doctor.
	 *
	 * @return the user ID of this doctor
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this doctor.
	 *
	 * @param userId the user ID of this doctor
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this doctor.
	 *
	 * @return the user uuid of this doctor
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this doctor.
	 *
	 * @param userUuid the user uuid of this doctor
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this doctor.
	 *
	 * @return the user name of this doctor
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this doctor.
	 *
	 * @param userName the user name of this doctor
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this doctor.
	 *
	 * @return the create date of this doctor
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this doctor.
	 *
	 * @param createDate the create date of this doctor
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this doctor.
	 *
	 * @return the modified date of this doctor
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this doctor.
	 *
	 * @param modifiedDate the modified date of this doctor
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this doctor.
	 *
	 * @return the name of this doctor
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this doctor.
	 *
	 * @param name the name of this doctor
	 */
	public void setName(String name);

	/**
	 * Returns the surname of this doctor.
	 *
	 * @return the surname of this doctor
	 */
	@AutoEscape
	public String getSurname();

	/**
	 * Sets the surname of this doctor.
	 *
	 * @param surname the surname of this doctor
	 */
	public void setSurname(String surname);

	/**
	 * Returns the image ID of this doctor.
	 *
	 * @return the image ID of this doctor
	 */
	public long getImageId();

	/**
	 * Sets the image ID of this doctor.
	 *
	 * @param imageId the image ID of this doctor
	 */
	public void setImageId(long imageId);

	/**
	 * Returns the middle name of this doctor.
	 *
	 * @return the middle name of this doctor
	 */
	@AutoEscape
	public String getMiddleName();

	/**
	 * Sets the middle name of this doctor.
	 *
	 * @param middleName the middle name of this doctor
	 */
	public void setMiddleName(String middleName);

	/**
	 * Returns the specialization of this doctor.
	 *
	 * @return the specialization of this doctor
	 */
	@AutoEscape
	public String getSpecialization();

	/**
	 * Sets the specialization of this doctor.
	 *
	 * @param specialization the specialization of this doctor
	 */
	public void setSpecialization(String specialization);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(salutem.doctor.model.Doctor doctor);

	@Override
	public int hashCode();

	@Override
	public CacheModel<salutem.doctor.model.Doctor> toCacheModel();

	@Override
	public salutem.doctor.model.Doctor toEscapedModel();

	@Override
	public salutem.doctor.model.Doctor toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}