/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package salutem.doctor.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the DoctorSchedule service. Represents a row in the &quot;doctor_DoctorSchedule&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link salutem.doctor.model.impl.DoctorScheduleModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link salutem.doctor.model.impl.DoctorScheduleImpl}.
 * </p>
 *
 * @author Aneta Andrzejewska
 * @see DoctorSchedule
 * @see salutem.doctor.model.impl.DoctorScheduleImpl
 * @see salutem.doctor.model.impl.DoctorScheduleModelImpl
 * @generated
 */
public interface DoctorScheduleModel extends BaseModel<DoctorSchedule> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a doctor schedule model instance should use the {@link DoctorSchedule} interface instead.
	 */

	/**
	 * Returns the primary key of this doctor schedule.
	 *
	 * @return the primary key of this doctor schedule
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this doctor schedule.
	 *
	 * @param primaryKey the primary key of this doctor schedule
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the schedule ID of this doctor schedule.
	 *
	 * @return the schedule ID of this doctor schedule
	 */
	public long getScheduleId();

	/**
	 * Sets the schedule ID of this doctor schedule.
	 *
	 * @param scheduleId the schedule ID of this doctor schedule
	 */
	public void setScheduleId(long scheduleId);

	/**
	 * Returns the doctor ID of this doctor schedule.
	 *
	 * @return the doctor ID of this doctor schedule
	 */
	public long getDoctorId();

	/**
	 * Sets the doctor ID of this doctor schedule.
	 *
	 * @param doctorId the doctor ID of this doctor schedule
	 */
	public void setDoctorId(long doctorId);

	/**
	 * Returns the create date of this doctor schedule.
	 *
	 * @return the create date of this doctor schedule
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this doctor schedule.
	 *
	 * @param createDate the create date of this doctor schedule
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this doctor schedule.
	 *
	 * @return the modified date of this doctor schedule
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this doctor schedule.
	 *
	 * @param modifiedDate the modified date of this doctor schedule
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the day of week of this doctor schedule.
	 *
	 * @return the day of week of this doctor schedule
	 */
	public int getDayOfWeek();

	/**
	 * Sets the day of week of this doctor schedule.
	 *
	 * @param dayOfWeek the day of week of this doctor schedule
	 */
	public void setDayOfWeek(int dayOfWeek);

	/**
	 * Returns the start time of this doctor schedule.
	 *
	 * @return the start time of this doctor schedule
	 */
	public double getStartTime();

	/**
	 * Sets the start time of this doctor schedule.
	 *
	 * @param startTime the start time of this doctor schedule
	 */
	public void setStartTime(double startTime);

	/**
	 * Returns the end time of this doctor schedule.
	 *
	 * @return the end time of this doctor schedule
	 */
	public double getEndTime();

	/**
	 * Sets the end time of this doctor schedule.
	 *
	 * @param endTime the end time of this doctor schedule
	 */
	public void setEndTime(double endTime);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(salutem.doctor.model.DoctorSchedule doctorSchedule);

	@Override
	public int hashCode();

	@Override
	public CacheModel<salutem.doctor.model.DoctorSchedule> toCacheModel();

	@Override
	public salutem.doctor.model.DoctorSchedule toEscapedModel();

	@Override
	public salutem.doctor.model.DoctorSchedule toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}